# Generated by Django 3.2 on 2021-10-27 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backApp', '0003_auto_20211027_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backApp.product'),
            preserve_default=False,
        ),
    ]
