# Generated by Django 3.2 on 2021-11-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backApp', '0005_auto_20211105_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='family_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='first_name',
        ),
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
