# Generated by Django 3.2 on 2021-11-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backApp', '0006_auto_20211105_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
