# Generated by Django 3.2 on 2021-11-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backApp', '0007_auto_20211105_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
