# Generated by Django 3.2 on 2021-11-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backApp', '0009_auto_20211107_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password2',
            field=models.CharField(default='', max_length=50),
        ),
    ]
