# Generated by Django 3.2 on 2021-11-07 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backApp', '0010_client_password2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backApp.cart'),
        ),
    ]
