# Generated by Django 3.2 on 2021-11-07 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backApp', '0011_alter_client_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='password2',
        ),
    ]
