# Generated by Django 3.2 on 2021-11-07 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backApp', '0014_auto_20211107_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='last_name',
            new_name='family_name',
        ),
    ]
